wandb_version: 1

agent:
  desc: null
  value:
    agent_args: {}
    max_steps: 1
    n_parallel_agents: null
algorithm:
  desc: null
  value:
    adv_estimator: grpo
    gamma: 1.0
    grouping_level: episode
    lam: 0.95
    norm_adv_by_std_in_grpo: false
    remove_constant_reward_groups: false
data:
  desc: null
  value:
    max_prompt_length: 2048
    max_response_length: 8192
    train_batch_size: 4
    train_files: /mlx_devbox/users/lixingzuo.26/MPRL/rllm/rllm/data/datasets/deepscaler_math/train_verl.parquet
    val_batch_size: 8
    val_files: /mlx_devbox/users/lixingzuo.26/MPRL/rllm/rllm/data/datasets/aime2024/test_verl.parquet
disable_thinking:
  desc: null
  value: false
env:
  desc: null
  value:
    env_args: {}
filter_token_mismatch:
  desc: null
  value: true
model:
  desc: null
  value:
    attn_implementation: null
    gradient_checkpointing: true
    lora_alpha: 64
    lora_dropout: 0.05
    lora_rank: 32
    lora_target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    name: /mnt/hdfs/lixingzuo/qwen_model/origin/Qwen3-4B-Instruct
    trust_remote_code: true
    use_lora: false
rollout:
  desc: null
  value:
    api_key: EMPTY
    base_url: http://127.0.0.1:8000/v1
    batch_size: 16
    batch_timeout_s: 0.05
    gpu_memory_utilization: 0.85
    mode: server
    tensor_parallel_size: 1
sampling:
  desc: null
  value:
    temperature: 0.6
    top_p: 0.95
trainer:
  desc: null
  value:
    default_local_dir: /tmp/rllm-swift-deepscaler-qwen3-4b-server
    experiment_name: deepscaler-qwen3-4b-server
    logger:
    - console
    - wandb
    project_name: rllm-swift
    save_freq: 20000
    test_freq: 20
    total_epochs: 1
    val_before_train: true
training:
  desc: null
  value:
    beta1: 0.9
    beta2: 0.95
    clip_ratio: 0.2
    eps: 1.0e-08
    gradient_accumulation_steps: 1
    group_size: 8
    learning_rate: 1.0e-06
    max_grad_norm: 1.0
    num_minibatches: 1
