set -x

export VLLM_ATTENTION_BACKEND=FLASH_ATTN
export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:False"
export VLLM_USE_V1=1
export VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
export VLLM_ENGINE_ITERATION_TIMEOUT_S=100000000000

# export MINIWOB_URL="file://<PATH_TO_MINIWOB_PLUSPLUS_CLONED_REPO>/miniwob/html/miniwob/"

# Find the directory where rllm package is located
RLLM_DIR=$(python3 -c "import rllm; import os; print(os.path.dirname(os.path.dirname(rllm.__file__)))")

python3 -m examples.miniwob.train_miniwob_agent \
    algorithm.adv_estimator=grpo \
    data.train_files=${RLLM_DIR}/data/rllm-miniwob/train.parquet \
    data.val_files=${RLLM_DIR}/data/rllm-miniwob/test.parquet \
    data.train_batch_size=8 \
    data.val_batch_size=128 \
    data.max_prompt_length=3072 \
    data.max_response_length=16384 \
    actor_rollout_ref.model.path=Qwen/Qwen3-1.7B \
    actor_rollout_ref.hybrid_engine=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.loss_agg_mode=seq-mean-token-sum-norm \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=24000 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.kl_loss_coef=0.003 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=1 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.mode="async" \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.temperature=0.7 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.65 \
    actor_rollout_ref.rollout.n=16 \
    actor_rollout_ref.rollout.val_kwargs.n=4 \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.7 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.entropy_coeff=0.002 \
    actor_rollout_ref.actor.ppo_epochs=1 \
    algorithm.kl_ctrl.kl_coef=0.001 \
    rllm.mask_truncated_samples=False \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='rllm-agent' \
    trainer.experiment_name='1.7b-miniwob_agent' \
    trainer.val_before_train=True \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=10 \
    trainer.default_hdfs_dir=null \
    rllm.rejection_sample.enable=True \
    rllm.rejection_sample.multiplier=2 \
    rllm.env.name=browsergym \
    rllm.agent.name=miniwobagent \
    rllm.agent.max_steps=15 \
    rllm.stepwise_advantage.enable=False \
    rllm.agent.trajectory_timeout=600 \
    rllm.disable_thinking=False \
    +rllm.agent.engine_args.retry_limit=5 \
    +rllm.agent.agent_args.use_accumulate_thinking=True \
    +rllm.agent.agent_args.use_full_conversation=True \
    +rllm.agent.agent_args.chat_mode=False \
    +rllm.agent.agent_args.use_html=True \
    +rllm.agent.agent_args.use_axtree=True \
    +rllm.agent.agent_args.use_screenshot=False \
    +rllm.agent.agent_args.cot_prompt=False \
    +rllm.agent.agent_args.use_reward_shaping=False \
    trainer.total_epochs=10